#!/usr/bin/env bash
# This script creates the file /var/run/myscript.pid and displays:
# - 'To infinity and beyond' indefinitely
# - 'I hate the kill command' when receiving a SIGINT signal
# - 'Y U no love me?!' when receiving a SIGINT signal
# Finally deletes the file /var/run/myscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal
pid_file="/var/run/myscript.pid"

cleanup_and_exit() {
        echo "Cleaning up and exiting..."
        if [ -f "$pid_file" ]; then
                rm "$pid_file"
        fi
        exit
}

trap 'echo "I hate the kill command" && cleanup_and_exit' SIGTERM
trap 'echo "Y U no love me?!" && cleanup_and_exit' SIGINT
trap 'cleanup_and_exit' SIGQUIT

mypid=$$
echo "$mypid" > "$pid_file"

while true; do
        echo "To infinity and beyond"
        sleep 2
done

