#!/usr/bin/env bash
# Displays contents of /etc/passwd using a short made up story with read and cut
file_path="/etc/passwd"

if [ -e "$file_path" ]; then
    while IFS=':' read -r username _ userid groupname home shell; do
        password=$(echo "$shell" | cut -d' ' -f1)
        user_info="more info about the user here: $username"
        
        echo "The user $username is part of the $userid gang, lives in $home and rides $shell."
        echo "$userid's place is protected by the passcode $password, $user_info"
    done < "$file_path"
else
    echo "The /etc/passwd file does not exist"
fi
