#!/usr/bin/env bash
#This script uses a while and if loop to display Best school 10 times
#But on the 9th interatiom, displays Best School and then Hi on a new line 
j=0
while [ $j -lt 10 ];
do
	echo "Best School"
	if [ $j -eq 8 ];
	then
		echo "Hi"
	fi
	((j++))
done
