#!/usr/bin/env bash
# This script displays number from 1 - 20, also:
# But it displays "bad luck from China" for the 4th loop iteration
# dispalys "bad luck from Japan" for the 9th loop iteration
# And displays "bad luck from Italy" for the 17th loop iteration
i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((i++))
done
