#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Displaying only the part of the name after the first dash
# Doesnot display hidden files
list="$(ls -A)"

for item in $list; do
        name=$(echo "$item" | cut -d '-' -f2)
        echo "$name"
done

